config/routes.rb
Assessable::Engine.routes.draw do


  resources :assessments do
    member do
      post :post
      get :clone
      get :display
    end
    collection do
      get :group
      get :clone_group
    end
    resources :questions, :only => [ :new] 
  end

  resources :questions, :only => [:show, :edit, :update, :destroy, :create] do
    resources :answers, :only => [ :new] 
    member do
      get :edit_answers
      get :clone
    end
  end
  resources :answers, :only => [:show, :edit, :update, :destroy, :create]
  
  root :to => "home#index"
  
end

app/models/assessable/answer.rb
module Assessable
  class Answer < ActiveRecord::Base
    belongs_to :question, :touch => true
    
    validates_numericality_of :value, :greater_than_or_equal_to => 0
    validates_presence_of :question_id
  end
end

app/models/assessable/assessing.rb
module Assessable
    
  class Assessing
    # This generic class provides a number of class methods that interface with Assessable without using namespacing.
    #   The modules/models it interfaces with are:
    #     Scoring module
    #       Score class
    #     Stash class
    
    # These methods could be copied to you own class
      
    ## Stash
    def self.get_post(id, session)
      # Equivilalant to Assessable::Stash.get(session).get_pos(id)
      # retrieves a post stored in a stash by a user defined id and session_id
      stash = Stash.get(session)
      post = stash.get_post(id) 
    end
    
    def self.set_post(id,post,session)
      # Equivilalant to Assessable::Stash.get(session).set_post(id,post)
      # Stores a post in a stash by a user defined id and session_id
      stash = Stash.get(session)
      stash.set_post(id,post)
    end
    
    def self.get_stash(session)
      # gets or creates a Stash instance by session_id
      stash = Stash.get(session)
    end
    
    def self.clear_stash(session)
      #clears (destroys) as stash instance by session id
      Stash.clear(session)
    end
    
    ## Scoring Module
    def self.score_assessment(published_assessment,post)
      # returns a scoring object
      scoring = Assessable::Scoring::Score.new(published_assessment,post)
      # The basic instantiation returns the object that has three attr_reader properties and on instance method
      #   scoring.post returns the original post
      #   scoring.all_answers returns an array of all answer ids as string. (@post["answer"].values.flatten)
      #   scoring.scores returns a scoring hash that contains raw and weighted scores for each question/answer(s) as well as total and percentage scores
      #   scoring.scored_post, appends the scores hash to the original post
    end
    
  end
  
end

app/controllers/assessable/answers_controller.rb
require_dependency "assessable/application_controller"

module Assessable
  class AnswersController < ApplicationController
    before_filter :load_resources, :except => :create
    
  
    # GET /answers/1
    # GET /answers/1.json
    def show
      #@answer = Answer.find(params[:id])
  
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @answer }
      end
    end
  
    # GET /answers/new
    # GET /answers/new.json
    def new
      max = @question.answers.maximum(:sequence) 
      @answer.sequence = max.nil? ? 1  : max + 1
  
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @answer }
      end
    end
  
    # GET /answers/1/edit
    def edit
      #@answer = Answer.find(params[:id])
    end
  
    # POST /answers
    # POST /answers.json
    def create
      @answer = Answer.new(answer_params)
  
      respond_to do |format|
        if @answer.save
          format.html { redirect_to @answer, notice: 'Answer was successfully created.' }
          format.json { render json: @answer, status: :created, location: @answer }
        else
          format.html { render action: "new" }
          format.json { render json: @answer.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PUT /answers/1
    # PUT /answers/1.json
    def update
      #@answer = Answer.find(params[:id])
  
      respond_to do |format|
        if @answer.update_attributes(answer_params)
          format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @answer.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /answers/1
    # DELETE /answers/1.json
    def destroy
      #@answer = Answer.find(params[:id])
      @answer.destroy
  
      respond_to do |format|
        format.html { redirect_to question_url(@answer.question_id) }
        format.json { head :no_content }
      end
    end
    
    private
    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:answer_text, :key, :other_question, :question_id, :requires_other, :sequence, :short_name, :text_eval, :value)
    end
    
    def load_resources
      if params[:id]
        @answer = Answer.find(params[:id])
        @question = @answer.question
      elsif params[:question_id]
        @question = Question.find(params[:question_id])
        @answer = @question.answers.build
      end
    end
    
  end
end

app/controllers/assessable/application_controller.rb
module Assessable
  class ApplicationController < ActionController::Base
  end
end

app/controllers/assessable/home_controller.rb
require_dependency "assessable/application_controller"

module Assessable
  class HomeController < ApplicationController

    def index
    end
  end
end

app/helpers/assessable/application_helper.rb
module Assessable
  module ApplicationHelper
    def status_options(status)
      if status.nil?
        status = ""
      end
      types = [""] + Assessable.config[:assessment_status_options]
      result = options_for_select(types,status.capitalize)
      return result.html_safe
    end

    def answer_type_options(answer_type)
      if answer_type.nil?
        answer_type = ""
      end
      types = %W( #{""} Radio Checkbox Select Select-multiple Text Textarea)
      result = options_for_select(types,answer_type.capitalize)
      return result.html_safe
    end
    
    def score_method_options(score_method)
      if score_method.nil?
        score_method = ""
      end
      types = %W( Value Sum Max None TextContains TextNumeric)
      result = options_for_select(types,score_method)
      return result.html_safe
    end
    
    def display_type_options(display_type,empty=false)
      if display_type.nil?
        display_type = ""
      end
      types = empty ? %W( #{""} List Inline None) : %W( List Inline None)
      result = options_for_select(types,display_type.capitalize)
      return result.html_safe
    end
    
    
    def truncateText(text,length = 40, where = "end")
      if text.nil?
        return text
      end
      text_length = text.length
      if text_length <= length
        return text
      end
      result = ""
      if where.downcase == "end"
        result = ( text.first(length)+"&hellip;")
      elsif where.downcase == "begin"
        result = ( text.last(length)+"&hellip;")
      else
        result = (text.first(length / 2)+"&hellip;"+ text.last(length / 2))
      end
      return result.html_safe
    end
    
  end
end

app/helpers/assessable/assessments_helper.rb
module Assessable
  module AssessmentsHelper
    
    def table_list(c1,c2)
      "<table><tr><td>#{c1}</td><td>#{c2}</td></tr></table>".html_safe
    end
    
    def wrap_row(c1,c2)
      "<tr><td>#{c1}</td><td>#{c2}</td></tr>".html_safe
    end
      
    def get_post_answer(a)
      answer_id = a['id'].to_s
      text = ""
      exists = false
      other = ""
      if @post
        #Answers from a previous application or session are in the Params collection - values are extracted
        #into the variables exist, other, and text 
        if !@post["all"].index(answer_id).nil?
          exists = true
          other = @post["other"][answer_id] if @post["other"]
          text = @post["text"][answer_id] if @post["text"]
        end
      end
      return text, exists, other
    end
    
    def render_instructions
      content_tag :fieldset, (content_tag(:legend,"Instructions") + @assessment["instructions"]).html_safe, class: "take-instructions"
    end
    
    def render_input(question,answer)
      # until this point, we don't know what the input tag is
      # it creates input tag
      result = ""
      text, exists, other =  get_post_answer(answer)
      case question["answer_tag"].downcase
      when "radio"
        required = question["score_method"].downcase == "none" ? "" : "required-one"
        behavior = question["requires_other"] ? "toggle_other" : ""
        result = radio_button_tag("post[answer][#{question["id"]}][]",answer["id"].to_s, exists,
         :class => required, :"data-behavior" => behavior , :id => "qa_#{question["id"]}_#{answer["id"]}")
      when "checkbox"
        required = question["score_method"].downcase == "none" ? "" : "required-one"
        behavior = answer["requires_other"] ? "toggle_other" : "none"
        result = check_box_tag("post[answer][#{question["id"]}][]",answer["id"].to_s, exists,
         :class => required, :"data-behavior" => behavior, :id => "qa_#{question["id"]}_#{answer["id"]}")
      when "textarea"
        required = question["score_method"].downcase == "none" ? "" : "required"
        hidden_elem = hidden_field_tag("post[answer][#{question["id"]}][]",answer["id"].to_s,:id => nil ) 
        result = hidden_elem + text_area_tag("post[text][#{answer["id"]}]",text,
         :class => required,  :id => "qa_#{question["id"]}_#{answer["id"]}")
      when /text/i
        required = question["score_method"].downcase == "none" ? "" : "required"
        hidden_elem = hidden_field_tag("post[answer][#{question["id"]}][]",answer["id"].to_s,:id => nil ) 
        result = hidden_elem + text_field_tag("post[text][#{answer["id"]}]",text,
         :class => required,  :id => "qa_#{question["id"]}_#{answer["id"]}")
      end
      return result 
    end
    # div inline
    #   table
    #     tr
    #       td input+answer
    #       td question
    #         div others
    # div list
    #   table
    #     tr
    #       td input
    #       td answer
    #         div other
    
    def render_select_tag(q)
      # it returns a select tag, with all options set and other divs, if any
      others = ""
      answers = q["answers"]
      options = ""
      answers.each do |answer|
        if answer['requires_other']
          others += render_other(answer) 
        end
        
        text, exists, other = get_post_answer(answer)
        
        sel = exists ? 'selected="selected"' : ""        
        options << "<option value=\"#{answer["id"]}\" #{sel}>#{answer["answer_text"]}</option>"
    
      end
      data_behavior = q["requires_other"] ? "toggle_other_sel" : ""
      mult = q["answer_tag"].downcase == "select" ? false : true
      required = q["score_method"].downcase == "none" ? "" : "required-one"
      
      itag = select_tag("post[answer][#{q["id"]}][]", options.html_safe, :id => "qa_#{q["id"]}", 
      :class => required, :include_blank => !mult, :multiple => mult, :"data-behavior" => data_behavior )
      return itag, others
    end
    
    def render_other(a)
      # it needs to build a text input for other question, including @post
      text, exists, other = get_post_answer(a)
      dsp = exists ? "block" : "none"
      
      tag = text_field_tag("post[other][#{a["id"].to_s}]",other, :id => "text_qa_#{a["question_id"]}_#{a["id"]}", :disabled => !exists)
      content_tag( :div, 
        (tag + a["answer_text"] + ":" + a["other_question"]).html_safe, 
        class: "take-other-question", id: "other_qa_#{a["question_id"]}_#{a["id"]}",style: "display:#{dsp}")
    end
  
    def render_question_text(q)
      content_tag :span, q['question_text'].html_safe, class: "take-question-text"
    end
    
    def render_inline(q)
      if !(q["answer_tag"] =~   /select/i).nil?
        itag, others = render_select_tag(q)
        answers = content_tag :span, itag, class: "take-select"
      else
        others = ""
        answers = ""
        q['answers'].each do |a|
          if a['requires_other']
            others += render_other(a) 
          end
          itag = render_input(q,a) + a['answer_text']
          answers += content_tag :span, itag, id: "take_answer_#{a['id']}", class: "take-inline-answer"
        end
      end
      content_tag :div, (table_list(answers,render_question_text(q)) + others.html_safe).html_safe, id: "take_question_#{q['id']}", class: 'take-question'
    end
    
    def render_list(q)
      if !(q["answer_tag"] =~   /select/i).nil?
        itag, others = render_select_tag(q)
        answers = content_tag :span, itag, class: "take-select"
        tbl = table_list(answers, others.html_safe).html_safe
        content_tag :div, (render_question_text(q) + tbl.html_safe).html_safe, id: "take_question_#{q['id']}", class: 'take-question'
      else
        answers = ""
        q['answers'].each do |a|
          other = a['requires_other'] ? render_other(a) : ""
          itag = render_input(q,a)
          answers += wrap_row(itag,a['answer_text']+other).html_safe
        end
        content_tag :div, (render_question_text(q) + content_tag(:table,answers.html_safe, class: "take-list")).html_safe, id: "take_question_#{q['id']}", class: 'take-question'
      end
    end
    
    def render_group(q)
      unless q["group_header"].blank?
        content_tag :div, q['group_header'], class: "take-group-header"
      else
        ""
      end
    end
    
    def render_question_instructions(q)
      unless q["instructions"].blank?
        content_tag :div, q['instructions'], class: "take-question-instructions"
      else
        ""
      end
    end
    
    def render_questions
      questions = ""
      @assessment['questions'].each do |q|
        unless q["answer_layout"].downcase == "none"
          questions += render_group(q)
          questions += render_question_instructions(q)
          # question requires_other set in question hash if any answer requires other
          q["answers"].map{|r| q["requires_other"] = r["requires_other"] if r["requires_other"]  }
          if q["answer_layout"].downcase == "inline"
            questions += render_inline(q)
          else
            questions += render_list(q)
          end
        end
      end
      content_tag :div, questions.html_safe, class: "take-questions"
    end
    
    def render_assessment(assessment_hash, post=nil)
      @assessment = assessment_hash
      @post = post
      questions = render_questions
      content_tag :div, (render_instructions + questions), class: "take-assessment", id: "take_assessment"
    end
    
    def score_summary(assmt,post)

      html = ""
      alt = true 
      ans_count = post['answer'].count
      assmt['questions'].each do |question|
        alt = !alt
        rclass = alt ? 'alt' : ''
        qkey = question['id'].to_s
        ans_array = question['answers'].map{|i| i['id']}
        ans = post['answer'][qkey]
        next if ans.nil?
        all = "["
        isText =  !(question['answer_tag'] =~ /text/i).nil?
        question_text = question['short_name'].blank? ? question['question_text'].slice(0,40) : question['short_name']
        question_text = "{#{question["id"]}} #{question_text}"
        answer_text = ""
        ans.each do |akey|
          akeyi = akey.to_i
          aidx = ans_array.index(akeyi)
          answ = question['answers'][aidx]
          answer_text = answ['short_name'].blank? ? answ['answer_text'].slice(0,20) : answ['short_name']
          if isText
            all << post['text'][akey] + ", " unless post['text'][akey].nil?
          else
            if answ['requires_other'] && post['other']
              all << answer_text + '{' + post['other'][akey] + '}, '
            else
              all << answer_text + ", "
            end
          end
        end
        all = all[0..-3] + "]"
        if post['critical']
          rclass = post['critical'].index(qkey).nil? ? rclass : (rclass += " failed"  )
        end
        rclass = "class=\"#{rclass}\"" unless rclass.blank?

        html << "<tr #{rclass}><td>#{question_text}</td><td>#{all}</td><td>#{post['scores'][qkey]['raw']}</td><td>#{post['scores'][qkey]['raw']}</td></tr>"
      end
      html << "<tr class=\"list-header\"><td></td><td>Total</td><td>#{post['scores']["total"]['raw']}</td><td>#{post['scores']["total"]['raw']}</td></tr>"
      
      return html.html_safe
    end  
    
    
  end
end

app/views/assessable/questions/_contains.html.haml
- text_eval = text_eval.nil? ? "" : text_eval
- @obj = Assessable::TextEval::Contains.new(text_eval)
- fform = @obj.format_form
.form-list
  %table
    - cnt = 0
    - wcnt = 0
    
    /- logger.debug "group count #{fform["groups"].count} #{fform["groups"].inspect}"
    -fform["groups"].each do |group|
      - grp = true
      /- logger.debug "group count #{cnt} #{group.inspect}"
      - group.each do |w|
        - wcnt += 1
        /- logger.debug "count #{cnt} #{wcnt}"
        %tr
          %th Word(s)
          %td
            = text_field_tag "match_#{seq}_#{wcnt}", w["words"],size: 35, class: "seq_#{seq}_match"
          %td
            - if (cnt > 0 && grp)
              - checked = true
              - grp = false
            -else
              - checked = false
            = check_box_tag "group_or_#{seq}_#{wcnt}", nil, checked
            Or Group
          %td
            = check_box_tag "word_or_#{seq}_#{wcnt}", nil, w["or"]
            Or Words
          %td 
            = check_box_tag "word_not_#{seq}_#{wcnt}", nil, w["not"]
            Not Words
      - cnt += 1
      
  %table
    - wcnt = 0
  
    -fform["partials"].each do |p|
      - wcnt += 1
      %tr
        %th Partial
        %td= text_field_tag "partial_match_#{seq}_#{wcnt}", p["words"],size: 35, class: "seq_#{seq}_partial"
        %th Percent
        %td= text_field_tag "partial_percent_#{seq}_#{wcnt}", p["percent"],size: 4
        %td
          = check_box_tag "partial_or_#{seq}_#{wcnt}", nil,p["or"]
          Or Words
        %td 
          = check_box_tag "partial_not_#{seq}_#{wcnt}", nil,p["not"]
          Not Words
  = button_to_function "Update Text Eval",nil, :id => "seq_#{seq}_update", "data-behavior" => "contains_update"
  = link_to_function "Cancel",nil, :id => "seq_#{seq}_cancel", "data-behavior" => "contains_cancel", :class => "breadcrumb"
      

app/views/assessable/questions/_form.html.haml
= form_for @question do |f|
  - if @question.errors.any?
    #error_explanation
      %h2= "#{pluralize(@question.errors.count, "error")} prohibited this question from being saved:"
      %ul
        - @question.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :assessment_id
    = f.hidden_field :assessment_id if @question.id.nil?
    = @question.assessment_id
  .field
    = f.label :sequence
    = f.number_field :sequence
  .field
    = f.label :question_text
    = f.text_area :question_text, :rows => 3
  .field
    = f.label :short_name
    = f.text_field :short_name
  .field
    = f.label :instructions
    = f.text_area :instructions, :rows => 3
  .field
    = f.label :group_header
    = f.text_area :group_header, :rows => 3
  .field
    = f.label :answer_tag
    = f.select :answer_tag, answer_type_options(@question.answer_tag)
  .field
    = f.label :answer_layout
    = f.select :answer_layout, display_type_options(@question.answer_layout)
  .field
    = f.label :weight
    = f.text_field :weight
  .field
    = f.label :critical
    = f.check_box :critical
  .field
    = f.label :min_critical
    = f.text_field :min_critical
  .field
    = f.label :score_method
    = f.select :score_method, score_method_options(@question.score_method)
  .field
    = f.label :key
    = f.text_field :key
  .actions
    = f.submit 'Save'

app/views/assessable/questions/_numeric.html.haml
- text_eval = text_eval.nil? ? "" : text_eval
- @obj = Assessable::TextEval::Numeric.new(text_eval)
.form-list
  %table
    %tr
      %th Match
      %td{:colspan => 3}= text_field_tag "numeric_match_#{seq}",@obj.match,size: 12
    - dcnt = 0
    -@obj.deltas.each do |delta,perc|
      - dcnt += 1
      %tr
        %th Delta
        %td= text_field_tag "delta_#{seq}_#{dcnt}",delta,size: 12, class: "seq_#{seq}_delta"
        %th Percent
        %td= text_field_tag "percent_#{seq}_#{dcnt}",perc,size: 12, class: "seq_#{seq}_percent"
    %tr
      %th New Delta
      %td= text_field_tag "delta_#{seq}_#{dcnt+1}","",size: 12, class: "seq_#{seq}_delta"
      %th New Percent
      %td= text_field_tag "percent_#{seq}_#{dcnt+1}","",size: 12, class: "seq_#{seq}_percent"
  = button_to_function "Update Numeric Eval",nil, :id => "seq_#{seq}_update", "data-behavior" => "numeric_update"
  = link_to_function "Cancel",nil, :id => "seq_#{seq}_cancel", "data-behavior" => "numeric_cancel", :class => "breadcrumb"
      

app/views/assessable/questions/edit.html.haml
%fieldset
  %legend Editing Question

  = render 'form'

.navbar
  = link_to 'Show', @question
  \|
  = link_to 'Assessment', assessment_path(@question.assessment_id)

app/views/assessable/questions/edit_answers.html.haml
%fieldset.show-list
  %legend Question
  %p#notice= notice
  .f-left
    %p
      %b Assessment:
      = @question.assessment_id
    %p
      %b Sequence:
      = @question.sequence
    %p
      %b Question text:
      = @question.question_text
    %p
      %b Short name:
      = @question.short_name
    %p
      %b Instructions:
      = @question.instructions
    %p
      %b Group header:
      = @question.group_header
  .f-left
    %p
      %b Answer tag:
      = @question.answer_tag
    %p
      %b Answer layout:
      = @question.answer_layout
    %p
      %b Weight:
      = @question.weight
    %p
      %b Critical:
      = @question.critical
    %p
      %b Min critical:
      = @question.min_critical
    %p
      %b Score method:
      = @question.score_method
    %p
      %b Key:
      = @question.key
  .f-clear
  .navbar

    = link_to 'Edit', edit_question_path(@question)
    \|
    = link_to 'Assessment', assessment_path(@question.assessment_id)
 
  = form_for(@question) do |f|
    - texteval = (@question.score_method == "TextContains") || (@question.score_method == "TextNumeric")
    - if @question.errors.any?
      #error_explanation
        %h2
          = pluralize(@question.errors.count, "error")
          prohibited this question from being saved:
        %ul
          - @question.errors.full_messages.each do |msg|
            %li= msg
    .index-list
      .actions
        = f.submit
        %span
          = @question.question_text.html_safe
      %table
        %tr.list-header
          %th Seq
          %th
            Answer Text/Short Name#{texteval ? "/Text Eval" : ""}
          %th Value
          %th &check; Other Question
          %th Delete
        - alt = true
        = f.fields_for :answers do |builder|
          - alt = !alt
          - new_ans = builder.object[:id].nil? ? "New " : ""
          <tr #{raw alt ? "class=\"alt\"" : ""}>
          %td
            = builder.text_field :sequence ,:size => 2
          %td
            %span.index-label
              = new_ans
              Answer:
            = builder.text_field :answer_text, :size => 50
            %br/
            %span.index-label Short Name:
            = builder.text_field :short_name, :size => 20
          %td
            = builder.text_field :value, :size => 2
          %td
            = builder.check_box :requires_other
            = builder.text_field :other_question, :size => 40
          %td
            %span
              - if !builder.object.answer_text.nil?
                = builder.check_box :_destroy, :"data-confirm" => "Are you sure?"
                = builder.label :_destroy, "Delete"
              - else
                \&nbsp;
          - if  texteval
            - behavior = @question.score_method == "TextContains" ? "edit_contains" : "edit_numeric"
            - partial = @question.score_method == "TextContains" ? "contains" : "numeric"
            %tr
              %td &nbsp;
              %td{:colspan => "3"}
                %span.index-label Text Eval:
                = builder.text_field :text_eval, :size => 110
              %td
                =link_to_function "Edit Helper",nil,"data-behavior" => behavior, :id => "eval_#{builder.object.sequence}", :class => "edit-button"
            %tr{id: "eval_#{builder.object.sequence}_div",:style => "display:none"}
              %td &nbsp;
              %td{:colspan => "4"}
                = render partial: partial, :locals => {:text_eval => builder.object.text_eval, :seq => builder.object.sequence}

app/views/assessable/questions/index.html.haml
%fieldset.index-list

  %legend 
    Assessment Questions
    = link_to 'New Question', new_assessment_question_path(@assessment)

  %table
    %tr.list-header
      %th Sequence
      %th Question
      %th Shortname
      %th Group
      %th Tag
      %th Layout
      %th Weight
      %th Critical
      %th Score
      %th Actions

    - @questions.each do |question|
      %tr
        %td= question.sequence
        %td= truncateText question.question_text
        %td= question.short_name
        %td= question.group_header
        %td= question.answer_tag
        %td= question.answer_layout
        %td= question.weight
        %td= question.critical
        %td= question.score_method
        %td
          = link_to 'Show', question
          = link_to 'Edit', edit_question_path(question)
          = link_to 'Destroy', question, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/assessable/questions/new.html.haml
%fieldset 
  %legend New Question

  = render 'form'
.navbar
  = link_to 'Cancel', assessment_path(@question.assessment_id)

app/views/assessable/questions/show.html.haml
%fieldset.show-list
  %legend Question
  %p#notice= notice
  .f-left
    %p
      %b Assessment:
      = @question.assessment_id
    %p
      %b Sequence:
      = @question.sequence
    %p
      %b Question text:
      = @question.question_text
    %p
      %b Short name:
      = @question.short_name
    %p
      %b Instructions:
      = @question.instructions
    %p
      %b Group header:
      = @question.group_header
  .f-left
    %p
      %b Answer tag:
      = @question.answer_tag
    %p
      %b Answer layout:
      = @question.answer_layout
    %p
      %b Weight:
      = @question.weight
    %p
      %b Critical:
      = @question.critical
    %p
      %b Min critical:
      = @question.min_critical
    %p
      %b Score method:
      = @question.score_method
    %p
      %b Key:
      = @question.key
  .f-clear
  .navbar

    = link_to 'Edit', edit_question_path(@question)
    \|
    = link_to 'Assessment', assessment_path(@question.assessment_id)
    \|
    = link_to 'Clone Question', clone_question_path(@question), :data => { :confirm => 'Are you sure?' }
 
  = render :template => "assessable/answers/index"